package musicmanager;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 * MusicManagerGUI.java
 * 12/03/24
 * @author Conor Judge
 */

public class MusicManagerGUI extends javax.swing.JFrame {
    private MusicManagerApp myApp; // Declare an instance variable
    private boolean repeatListEnabled = false; // Variable to track if repeat list is enabled
    
    
    
    public MusicManagerGUI() {
        initComponents();
        myApp = new MusicManagerApp(); // Initialize the instance variable
    }

    // Get methods for accessing GUI components
    //Gets the button used for adding songs
    public JButton getAddBTN() {
        return addBTN;
    }
    
    //Gets the text field for entering songs to add
    public JTextField getAddTF() {
        return addTF;
    }
    
    //Gets the button used for deleting songs
    public JButton getDeleteBTN() {
        return deleteBTN;
    }
    
    //Gets the text field for entering songs to delete
    public JTextField getDeleteTF() {
        return deleteTF;
    }

    //Gets the button used for moving songs to Genre A Playlist
    public JButton getMove2BTN() {
        return move2BTN;
    }
    
    //Gets the button used for moving songs to Genre B Playlist
    public JButton getMove3BTN() {
        return move3BTN;
    }
    
    //Gets the label for search
    public JLabel getSearchLBL() {
        return searchLBL;
    }
    
    //Gets the button used for searching songs
    public JButton getSearchBTN() {
        return searchBTN;
    }
    
    //Gets the text field for entering search queries
    public JTextField getSearchTF() {
        return searchTF;
    }
    
    //Gets the button used for printing Liked Playlist
    public JButton getPrintList1BTN() {
        return printList1BTN;
    }
    
    //Gets the button used for printing Genre A
    public JButton getPrintList2BTN() {
        return printList2BTN;
    }
    
    //Gets the button used for toggling repeat list functionality
    public JToggleButton getPrintList3BTN() {
        return printList3BTN;
    }
    
    //Gets the toggle button used for toggling repeat list functionality
    public JToggleButton getRepeatTGL() {
        return repeatTGL;
    }
    
    //Gets the text area used for displaying output
    public JTextArea getOutputTextArea() {
        return outputTextArea;
    }
    
    //Gets the button used for clearing the display area
    public JButton getClearBTN() {
        return clearBTN;
    }
    
    //Gets the button used for exiting the application
    public JButton getExitBTN() {
        return exitBTN;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        addBTN = new javax.swing.JButton();
        deleteTF = new javax.swing.JTextField();
        deleteBTN = new javax.swing.JButton();
        searchLBL = new javax.swing.JLabel();
        clearBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        exitBTN = new javax.swing.JButton();
        repeatTGL = new javax.swing.JToggleButton();
        printList1BTN = new javax.swing.JButton();
        move2BTN = new javax.swing.JButton();
        printList2BTN = new javax.swing.JButton();
        move3BTN = new javax.swing.JButton();
        addLBL = new javax.swing.JLabel();
        printList3BTN = new javax.swing.JToggleButton();
        deleteLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        searchLBL.setText("Search a song:");

        clearBTN.setText("CLEAR");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("SEARCH");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        repeatTGL.setText("REPEAT");
        repeatTGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatTGLActionPerformed(evt);
            }
        });

        printList1BTN.setText("LIKED SONGS");
        printList1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printList1BTNActionPerformed(evt);
            }
        });

        move2BTN.setText("MOVE TO GENRE A");
        move2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                move2BTNActionPerformed(evt);
            }
        });

        printList2BTN.setText("GENRE A");
        printList2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printList2BTNActionPerformed(evt);
            }
        });

        move3BTN.setText("MOVE TO GENRE B");
        move3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                move3BTNActionPerformed(evt);
            }
        });

        addLBL.setText("Add a song to liked Playlist:");

        printList3BTN.setText("GENRE B");
        printList3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printList3BTNActionPerformed(evt);
            }
        });

        deleteLBL.setText("Delete a song:");

        jLabel1.setText("Display Playlist:");

        jLabel2.setText("Set Playlist to Repeat:");

        titleLBL.setText("Music Manager");

        jLabel3.setText("Move Song from Liked:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(clearBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBTN)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchLBL)
                                    .addComponent(deleteLBL))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(293, 293, 293)
                                        .addComponent(printList2BTN)
                                        .addGap(30, 30, 30)
                                        .addComponent(printList3BTN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(411, 411, 411)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(deleteBTN))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(addBTN)
                                                .addComponent(searchBTN))))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addLBL)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addTF, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(titleLBL)
                                    .addComponent(searchTF)
                                    .addComponent(deleteTF))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(repeatTGL)
                                            .addComponent(printList1BTN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(move2BTN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(move3BTN)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleLBL)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLBL)
                    .addComponent(addTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBTN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN)
                    .addComponent(searchLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBTN)
                    .addComponent(deleteLBL))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(printList2BTN)
                    .addComponent(printList3BTN)
                    .addComponent(printList1BTN))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(repeatTGL))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(move2BTN)
                    .addComponent(move3BTN)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBTN)
                    .addComponent(exitBTN))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // Gets the text from the JTextField
        String newItem = addTF.getText(); 
        // Calls the addItem method of MusicManagerApp instance
        myApp.addItem(newItem); 
        // Clears the text field after adding
        addTF.setText(""); 
    }//GEN-LAST:event_addBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
         // Gets the text from the JTextField
        String itemToDelete = deleteTF.getText();
         // Calls the deleteItem method of MusicManagerApp instance
        myApp.deleteItem(itemToDelete);
         // Clears the text field after deleting
        deleteTF.setText("");
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // Clears the text area
        outputTextArea.setText(""); 
    }//GEN-LAST:event_clearBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // Gets the text from the JTextField
        String searchQuery = searchTF.getText();
        // Calls the searchItem method of MusicManagerApp instance
        myApp.searchItem(searchQuery); 
        // Clears the text field after searching
        searchTF.setText(""); 
    }//GEN-LAST:event_searchBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // Terminates the program
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void repeatTGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatTGLActionPerformed
        // Updates repeatListEnabled variable
        repeatListEnabled = repeatTGL.isSelected(); 
    }//GEN-LAST:event_repeatTGLActionPerformed

    private void printList1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printList1BTNActionPerformed
        // Calls the printList method of the MusicManagerApp instance with 1 as the argument
        myApp.printList(1);
    }//GEN-LAST:event_printList1BTNActionPerformed

    private void move2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_move2BTNActionPerformed
        // Calls moveLastItemToList2 method of MusicManagerApp when moveToList2BTN is clicked
        myApp.moveLastItemToList2();
    }//GEN-LAST:event_move2BTNActionPerformed

    private void printList2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printList2BTNActionPerformed
        // Calls the printList method of MusicManagerApp instance with 2 as the argument
        myApp.printList(2);
    }//GEN-LAST:event_printList2BTNActionPerformed

    private void move3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_move3BTNActionPerformed
        // Calls moveLastItemToList3 method of MusicManagerApp when moveToList3BTN is clicked
        myApp.moveLastItemToList3();
    }//GEN-LAST:event_move3BTNActionPerformed

    private void printList3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printList3BTNActionPerformed
        // Calls the printList method of MusicManagerApp instance with 3 as the argument
        myApp.printList(3); 
    }//GEN-LAST:event_printList3BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel addLBL;
    private javax.swing.JTextField addTF;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel deleteLBL;
    private javax.swing.JTextField deleteTF;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton move2BTN;
    private javax.swing.JButton move3BTN;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton printList1BTN;
    private javax.swing.JButton printList2BTN;
    private javax.swing.JToggleButton printList3BTN;
    private javax.swing.JToggleButton repeatTGL;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel searchLBL;
    private javax.swing.JTextField searchTF;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
